---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/developers":
    get:
      summary: list developers
      responses:
        '200':
          description: successful
    post:
      summary: create developer
      responses:
        '200':
          description: successful
  "/api/v1/developers/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show developer
      responses:
        '200':
          description: successful
    patch:
      summary: update developer
      responses:
        '200':
          description: successful
    put:
      summary: update developer
      responses:
        '200':
          description: successful
    delete:
      summary: delete developer
      responses:
        '200':
          description: successful
  "/api/v1/reservations":
    get:
      summary: list reservations
      responses:
        '200':
          description: successful
    post:
      summary: create reservation
      responses:
        '200':
          description: successful
  "/api/v1/reservations/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show reservation
      responses:
        '200':
          description: successful
    patch:
      summary: update reservation
      responses:
        '200':
          description: successful
    put:
      summary: update reservation
      responses:
        '200':
          description: successful
    delete:
      summary: delete reservation
      responses:
        '200':
          description: successful
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
